# Generated by Django 2.2.2 on 2019-07-06 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citydict',
            name='description',
            field=models.CharField(default='', max_length=200, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='citydict',
            name='name',
            field=models.CharField(default='', max_length=20, verbose_name='城市'),
        ),
    ]
