# Generated by Django 2.2.2 on 2019-07-04 13:14

from django.db import migrations, models
import froala_editor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='课程名称')),
                ('description', models.CharField(max_length=300, verbose_name='课程描述')),
                ('detail', froala_editor.fields.FroalaField(default='')),
                ('rank', models.CharField(choices=[('cj', '初级'), ('zj', '中级'), ('gj', '高级')], max_length=2, verbose_name='课程等级')),
                ('learn_time', models.IntegerField(default=0, verbose_name='时长')),
                ('study_count', models.IntegerField(default=0, verbose_name='学习人数')),
                ('favourite_count', models.IntegerField(default=0, verbose_name='收藏人数')),
                ('click_count', models.IntegerField(default=0, verbose_name='点击次数')),
            ],
        ),
    ]
