# Generated by Django 2.2.2 on 2019-07-05 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20190704_2121'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Course',
        ),
    ]
