# Generated by Django 2.2.2 on 2019-07-05 07:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_auto_20190705_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 5, 15, 26, 48, 917171), verbose_name=''),
        ),
    ]
