# Generated by Django 2.2.2 on 2019-07-05 09:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_auto_20190705_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 5, 17, 5, 54, 98277), verbose_name=''),
        ),
    ]
