# Generated by Django 2.2.2 on 2019-07-05 12:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_auto_20190705_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 5, 20, 29, 9, 921418), verbose_name=''),
        ),
    ]
