# Generated by Django 2.2.2 on 2019-07-06 00:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_auto_20190705_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 6, 8, 52, 13, 33798), verbose_name=''),
        ),
    ]
