# Generated by Django 2.2.2 on 2019-07-06 02:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0011_auto_20190706_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 6, 10, 45, 32, 962707), verbose_name=''),
        ),
    ]
