# Generated by Django 2.2.2 on 2019-07-06 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0016_auto_20190706_1631'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='study_count',
            new_name='students',
        ),
    ]
