# Generated by Django 2.2.2 on 2019-07-07 09:57

import apps.course.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0017_auto_20190706_2113'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Chapter',
            new_name='Lesson',
        ),
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(default='image/default.png', upload_to=apps.course.models.course_image_upload_path, verbose_name='封面图'),
        ),
    ]
