# Generated by Django 2.2.2 on 2019-07-07 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0018_auto_20190707_0957'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='click_count',
            new_name='click_nums',
        ),
    ]
