# Generated by Django 2.2.2 on 2019-07-07 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0020_course_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='chapter',
            new_name='lesson',
        ),
    ]
