# Generated by Django 2.2.2 on 2019-07-07 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0021_auto_20190707_1052'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='favourite_count',
            new_name='fav_nums',
        ),
    ]
