# Generated by Django 2.2.2 on 2019-07-04 12:42

from django.db import migrations
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='content',
            field=froala_editor.fields.FroalaField(default=''),
        ),
    ]
