# Generated by Django 2.2.2 on 2019-07-04 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_userprofile_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='content',
        ),
    ]
