# Generated by Django 2.2.2 on 2019-07-05 09:05

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_auto_20190705_1705'),
        ('user', '0005_auto_20190705_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='favourite_course',
            field=models.ManyToManyField(related_name='user_favourite_course', through='user.FavouriteCourse', to='course.Course'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='favourite_organization',
            field=models.ManyToManyField(related_name='user_favourite_organization', through='user.FavouriteOrganization', to='organization.Organization'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='favourite_teacher',
            field=models.ManyToManyField(related_name='user_favourite_teacher', through='user.FavouriteTeacher', to='organization.Teacher'),
        ),
        migrations.CreateModel(
            name='UserComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(default='', max_length=200, verbose_name='评论')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Course')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '评论',
                'verbose_name_plural': '评论',
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='comments',
            field=models.ManyToManyField(related_name='user_comment', through='user.UserComment', to='course.Course'),
        ),
    ]
