# Generated by Django 2.2.2 on 2019-07-06 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20190706_1953'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='profile_photo',
            new_name='image',
        ),
    ]
